sudo: required
services:
    - docker

before_install:
    - docker build -t sadovecki/react-test -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true sadovecki/react-test npm test -- --coverage

after_success:
    - docker build -t sadovecki/multi-client ./client
    - docker build -t sadovecki/multi-nginx ./nginx
    - docker build -t sadovecki/multi-server ./server
    - docker build -t sadovecki/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to the hub.docker.com
    - docker push sadovecki/multi-client
    - docker push sadovecki/multi-nginx
    - docker push sadovecki/multi-server
    - docker push sadovecki/multi-worker